### ISSUE TITLE
Missing Objects

### ISSUE THREAD

**Issue by wraith1385** [CollinHeist/TitleCardMaker#161]
Getting the below error after running pipenv run python main.py --run to verify that the required packages have been installed.

Traceback (most recent call last):
  File "/home/wraith1385/TitleCardMaker/main.py", line 13, in <module>
    from modules.PreferenceParser import PreferenceParser
  File "/home/wraith1385/TitleCardMaker/modules/PreferenceParser.py", line 11, in <module>
    from modules.Show import Show
  File "/home/wraith1385/TitleCardMaker/modules/Show.py", line 14, in <module>
    from modules.RemoteCardType import RemoteCardType
  File "/home/wraith1385/TitleCardMaker/modules/RemoteCardType.py", line 10, in <module>
    class RemoteCardType:
  File "/home/wraith1385/TitleCardMaker/modules/RemoteCardType.py", line 25, in RemoteCardType
    LOADED = TinyDB(TEMP_DIR / 'remote_assets.json')
  File "/home/wraith1385/.local/share/virtualenvs/TitleCardMaker-7O26HxdJ/lib/python3.9/site-packages/tinydb/database.py", line 94, in __init__
    self._storage: Storage = storage(*args, **kwargs)
  File "/home/wraith1385/.local/share/virtualenvs/TitleCardMaker-7O26HxdJ/lib/python3.9/site-packages/tinydb/storages.py", line 102, in __init__
    touch(path, create_dirs=create_dirs)
  File "/home/wraith1385/.local/share/virtualenvs/TitleCardMaker-7O26HxdJ/lib/python3.9/site-packages/tinydb/storages.py", line 31, in touch
    with open(path, 'a'):
FileNotFoundError: [Errno 2] No such file or directory: '/home/wraith1385/TitleCardMaker/modules/.objects/remote_assets.json'

**Desktop of the machine running the TitleCardMaker:**
 - OS: Ubuntu
 - Version 20.04
 - Are you creating cards on a remote/external drive/mount? - No

**Comment by CollinHeist** [comment]
Thanks! You can fix this by creating a `.objects` directory under `modules`. I'll push a fix on the develop branch here shortly

**Comment by wraith1385** [comment]
Thanks, that fixed it.
