### ISSUE TITLE
Season Poster Generation throw error "name 'value' is not defined"

### ISSUE THREAD

**Issue by 666dsa666** [CollinHeist/TitleCardMaker#174]
**Describe the bug**
Bug 2 : Season Poster Generation throw error : 
`     season_posters:
      create: true
      titles:
        0: Specials
        1: season_1.0
        2: season_2.0
      font:
        file: ./fonts/Mr. Robot.ttf
        color: red
        kerning: 105%
        fize: 95%`
Will throw this error : 
`Creating Title Cards for "Mr. Robot":    0%|          | 0/1 [00:00, ?it/s] 
Traceback (most recent call last):                                        
  File "/maker/main.py", line 135, in <module>
    run()
  File "/maker/main.py", line 130, in run
    tcm.run()
  File "/maker/modules/Manager.py", line 264, in run
    self.create_season_posters()
  File "/maker/modules/Manager.py", line 194, in create_season_posters
    show.create_season_posters()
  File "/maker/modules/Show.py", line 716, in create_season_posters
    poster_set = SeasonPosterSet(
  File "/maker/modules/SeasonPosterSet.py", line 63, in __init__
    self.__read_font(poster_config.get('font', {}))
  File "/maker/modules/SeasonPosterSet.py", line 88, in __read_font
    if (not isinstance(value, str)
NameError: name 'value' is not defined`

**To Reproduce**
Use wiki example for Season Poster Generation

**Expected behavior**
Season Poster Generation

**Screenshots**

**Config File**

**Series YAML File(s)**
[tv.txt](https://github.com/CollinHeist/TitleCardMaker/files/8892357/tv.txt)

**Desktop of the machine running the TitleCardMaker:**
Unraid 6.10.2

**ImageMagick:**
N/A

**Additional context**
Using examples for Mr. Robot, haven't tried another serie as this seems to be the most complete exemple in the wiki

**Comment by CollinHeist** [comment]
Thank you, I'll fix this shortly
